name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Prepare GitHub Pages files
      run: |
        # Copiar versão standalone
        cp standalone.html dist/
        
        # Copiar documentação
        cp README.md dist/
        cp INSTALL.md dist/
        cp TROUBLESHOOTING.md dist/
        
        # Usar página inicial personalizada como index principal
        cp public/index-pages.html dist/pages.html
        
        # Renomear o index.html do Vue para app.html
        mv dist/index.html dist/app.html
        
        # Usar a página de seleção como index principal
        cp public/index-pages.html dist/index.html
        
        # Ajustar links na página inicial
        sed -i 's|href="./index.html"|href="./app.html"|g' dist/index.html
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
