name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies with yarn
      run: |
        npm install -g yarn
        yarn install
        
    - name: Build project
      run: yarn build
      
    - name: Prepare GitHub Pages files
      run: |
        # Copiar versão standalone
        cp standalone.html dist/
        
        # Copiar documentação
        cp README.md dist/
        cp INSTALL.md dist/
        cp TROUBLESHOOTING.md dist/
        cp GITHUB-PAGES.md dist/
        cp GITHUB-PAGES-MANUAL.md dist/
        
        # Renomear o index.html do Vue para vue-app.html
        mv dist/index.html dist/vue-app.html
        
        # Criar index.html principal
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="pt-BR">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Matemática Divertida - Para Crianças</title>
          <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:wght@400;700&display=swap" rel="stylesheet">
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
              font-family: 'Comic Neue', cursive;
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              min-height: 100vh;
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              padding: 2rem;
            }
            .container {
              background: rgba(255, 255, 255, 0.95);
              border-radius: 20px;
              padding: 3rem;
              box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
              text-align: center;
              max-width: 600px;
              width: 100%;
            }
            .title {
              font-size: 2.5rem;
              color: #4a5568;
              margin-bottom: 1rem;
            }
            .subtitle {
              font-size: 1.2rem;
              color: #666;
              margin-bottom: 2rem;
            }
            .versions {
              display: grid;
              grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
              gap: 2rem;
              margin: 2rem 0;
            }
            .version-card {
              background: linear-gradient(45deg, #667eea, #764ba2);
              color: white;
              padding: 2rem;
              border-radius: 15px;
              text-decoration: none;
              transition: all 0.3s ease;
              box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
              display: block;
            }
            .version-card:hover {
              transform: translateY(-5px);
              box-shadow: 0 8px 25px rgba(0, 0, 0, 0.3);
            }
            .version-card.standalone {
              background: linear-gradient(45deg, #56ab2f, #a8e6cf);
            }
            .version-title {
              font-size: 1.5rem;
              font-weight: bold;
              margin-bottom: 1rem;
            }
            .version-description {
              font-size: 1rem;
              line-height: 1.5;
            }
            .footer {
              margin-top: 2rem;
              color: #666;
              font-size: 0.9rem;
            }
            @media (max-width: 768px) {
              .title { font-size: 2rem; }
              .container { padding: 2rem; margin: 1rem; }
              .versions { grid-template-columns: 1fr; gap: 1rem; }
            }
          </style>
        </head>
        <body>
          <div class="container">
            <h1 class="title">🧮 Matemática Divertida! 🎉</h1>
            <p class="subtitle">Escolha a versão que você prefere usar:</p>
            
            <div class="versions">
              <a href="./vue-app.html" class="version-card">
                <div class="version-title">🚀 Versão Vue.js</div>
                <div class="version-description">
                  Aplicação completa com Vue.js e Vite
                </div>
              </a>
              
              <a href="./standalone.html" class="version-card standalone">
                <div class="version-title">⚡ Versão Standalone</div>
                <div class="version-description">
                  Arquivo único, funciona em qualquer lugar
                </div>
              </a>
            </div>
            
            <div class="footer">
              <p>© 2025 Ítalo Moura - Desenvolvido com 💙 AWS Amazon Q CLI</p>
            </div>
          </div>
        </body>
        </html>
        EOF
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
