name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Prepare GitHub Pages files
      run: |
        # Copiar vers칚o standalone
        cp standalone.html dist/
        
        # Copiar documenta칞칚o
        cp README.md dist/
        cp INSTALL.md dist/
        cp TROUBLESHOOTING.md dist/
        cp GITHUB-PAGES.md dist/
        cp GITHUB-PAGES-MANUAL.md dist/
        
        # Copiar p치gina de sele칞칚o
        cp public/index-pages.html dist/
        
        # Criar index.html que redireciona para p치gina de sele칞칚o
        cat > dist/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="pt-BR">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Matem치tica Divertida - Redirecionando...</title>
          <style>
            body {
              font-family: 'Comic Neue', cursive;
              background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
              display: flex;
              justify-content: center;
              align-items: center;
              height: 100vh;
              margin: 0;
              color: white;
              text-align: center;
            }
            .loading {
              font-size: 1.5rem;
            }
          </style>
        </head>
        <body>
          <div class="loading">
            游빑 Carregando Matem치tica Divertida... 游꿀
          </div>
          <script>
            // Redirecionar para a p치gina de sele칞칚o
            setTimeout(() => {
              window.location.href = './index-pages.html';
            }, 1000);
          </script>
        </body>
        </html>
        EOF
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
